name: SlapperParticles
version: 1.0.2
api: 5.0.0
main: xqwtxon\SlapperParticles\Main
src-namespace-prefix: xqwtxon\SlapperParticles
depend: Slapper
author: xqwtxon
description: Slapper can now have particles!
