name: SlapperParticles
version: 1.0.2
api: 5.0.0
main: ReinfyTeam\SlapperParticles\Main
src-namespace-prefix: ReinfyTeam\SlapperParticles
depend: Slapper
author: ReinfyTeam
description: Slapper can now have particles!
